-- Starter ingredient vocabulary: vegetarian and vegan only, no meat or fish.
-- Seeded into every existing household. Re-runnable: an entry a household
-- already has is left alone, so nothing here overwrites a curated name.

insert into public.ingredients (household_id, name, section, food_type)
select h.id, v.name, v.section, v.food_type
from public.households h
cross join (values
  ('Pomidorai', 'Produce', 'Vegetables'),
  ('Vyšniniai pomidorai', 'Produce', 'Vegetables'),
  ('Agurkai', 'Produce', 'Vegetables'),
  ('Svogūnai', 'Produce', 'Vegetables'),
  ('Žali svogūnai', 'Produce', 'Vegetables'),
  ('Raudonieji svogūnai', 'Produce', 'Vegetables'),
  ('Česnakai', 'Produce', 'Vegetables'),
  ('Morkos', 'Produce', 'Vegetables'),
  ('Bulvės', 'Produce', 'Vegetables'),
  ('Saldžiosios bulvės', 'Produce', 'Vegetables'),
  ('Cukinijos', 'Produce', 'Vegetables'),
  ('Baklažanai', 'Produce', 'Vegetables'),
  ('Paprikos', 'Produce', 'Vegetables'),
  ('Brokoliai', 'Produce', 'Vegetables'),
  ('Žiediniai kopūstai', 'Produce', 'Vegetables'),
  ('Kopūstai', 'Produce', 'Vegetables'),
  ('Raudonieji kopūstai', 'Produce', 'Vegetables'),
  ('Kiniški kopūstai', 'Produce', 'Vegetables'),
  ('Burokėliai', 'Produce', 'Vegetables'),
  ('Ridikėliai', 'Produce', 'Vegetables'),
  ('Salierai', 'Produce', 'Vegetables'),
  ('Porai', 'Produce', 'Vegetables'),
  ('Špinatai', 'Produce', 'Vegetables'),
  ('Rukola', 'Produce', 'Vegetables'),
  ('Salotos', 'Produce', 'Vegetables'),
  ('Grybai', 'Produce', 'Vegetables'),
  ('Pievagrybiai', 'Produce', 'Vegetables'),
  ('Šitake grybai', 'Produce', 'Vegetables'),
  ('Moliūgai', 'Produce', 'Vegetables'),
  ('Ropės', 'Produce', 'Vegetables'),
  ('Pastarnokai', 'Produce', 'Vegetables'),
  ('Imbieras', 'Produce', 'Vegetables'),
  ('Čili pipirai', 'Produce', 'Vegetables'),
  ('Kukurūzai', 'Produce', 'Vegetables'),
  ('Šparaginės pupelės', 'Produce', 'Vegetables'),
  ('Avokadai', 'Produce', 'Vegetables'),
  ('Cukinijų žiedai', 'Produce', 'Vegetables'),
  ('Citrinos', 'Produce', 'Fruit'),
  ('Laimai', 'Produce', 'Fruit'),
  ('Apelsinai', 'Produce', 'Fruit'),
  ('Obuoliai', 'Produce', 'Fruit'),
  ('Kriaušės', 'Produce', 'Fruit'),
  ('Bananai', 'Produce', 'Fruit'),
  ('Braškės', 'Produce', 'Fruit'),
  ('Mėlynės', 'Produce', 'Fruit'),
  ('Avietės', 'Produce', 'Fruit'),
  ('Vynuogės', 'Produce', 'Fruit'),
  ('Granatai', 'Produce', 'Fruit'),
  ('Mangai', 'Produce', 'Fruit'),
  ('Bazilikas', 'Produce', 'Herbs & spices'),
  ('Krapai', 'Produce', 'Herbs & spices'),
  ('Petražolės', 'Produce', 'Herbs & spices'),
  ('Kalendros lapai', 'Produce', 'Herbs & spices'),
  ('Mėtos', 'Produce', 'Herbs & spices'),
  ('Rozmarinas', 'Produce', 'Herbs & spices'),
  ('Čiobreliai', 'Produce', 'Herbs & spices'),
  ('Šalavijas', 'Produce', 'Herbs & spices'),
  ('Makaronai', 'Pantry', 'Pasta'),
  ('Spagečiai', 'Pantry', 'Pasta'),
  ('Orzo', 'Pantry', 'Pasta'),
  ('Penne', 'Pantry', 'Pasta'),
  ('Fusilli', 'Pantry', 'Pasta'),
  ('Lazanijos lakštai', 'Pantry', 'Pasta'),
  ('Ryžių makaronai', 'Pantry', 'Pasta'),
  ('Udon makaronai', 'Pantry', 'Pasta'),
  ('Soba makaronai', 'Pantry', 'Pasta'),
  ('Ryžiai', 'Pantry', 'Grains'),
  ('Basmati ryžiai', 'Pantry', 'Grains'),
  ('Jazminų ryžiai', 'Pantry', 'Grains'),
  ('Rudieji ryžiai', 'Pantry', 'Grains'),
  ('Sušio ryžiai', 'Pantry', 'Grains'),
  ('Bulguras', 'Pantry', 'Grains'),
  ('Kuskusas', 'Pantry', 'Grains'),
  ('Kvinoja', 'Pantry', 'Grains'),
  ('Grikiai', 'Pantry', 'Grains'),
  ('Perlinės kruopos', 'Pantry', 'Grains'),
  ('Avižiniai dribsniai', 'Pantry', 'Grains'),
  ('Miltai', 'Pantry', 'Grains'),
  ('Pilno grūdo miltai', 'Pantry', 'Grains'),
  ('Kukurūzų krakmolas', 'Pantry', 'Grains'),
  ('Panko džiūvėsėliai', 'Pantry', 'Grains'),
  ('Džiūvėsėliai', 'Pantry', 'Grains'),
  ('Polenta', 'Pantry', 'Grains'),
  ('Avinžirniai', 'Pantry', 'Legumes'),
  ('Juodosios pupelės', 'Pantry', 'Legumes'),
  ('Raudonosios pupelės', 'Pantry', 'Legumes'),
  ('Baltosios pupelės', 'Pantry', 'Legumes'),
  ('Lęšiai', 'Pantry', 'Legumes'),
  ('Raudonieji lęšiai', 'Pantry', 'Legumes'),
  ('Žali lęšiai', 'Pantry', 'Legumes'),
  ('Sojos pupelės', 'Pantry', 'Legumes'),
  ('Graikiniai riešutai', 'Pantry', 'Nuts & seeds'),
  ('Migdolai', 'Pantry', 'Nuts & seeds'),
  ('Anakardžiai', 'Pantry', 'Nuts & seeds'),
  ('Žemės riešutai', 'Pantry', 'Nuts & seeds'),
  ('Lazdyno riešutai', 'Pantry', 'Nuts & seeds'),
  ('Saulėgrąžų sėklos', 'Pantry', 'Nuts & seeds'),
  ('Moliūgų sėklos', 'Pantry', 'Nuts & seeds'),
  ('Chia sėklos', 'Pantry', 'Nuts & seeds'),
  ('Linų sėmenys', 'Pantry', 'Nuts & seeds'),
  ('Sezamai', 'Pantry', 'Nuts & seeds'),
  ('Pistacijos', 'Pantry', 'Nuts & seeds'),
  ('Alyvuogių aliejus', 'Pantry', 'Oils & condiments'),
  ('Saulėgrąžų aliejus', 'Pantry', 'Oils & condiments'),
  ('Sezamų aliejus', 'Pantry', 'Oils & condiments'),
  ('Kokosų aliejus', 'Pantry', 'Oils & condiments'),
  ('Rapsų aliejus', 'Pantry', 'Oils & condiments'),
  ('Sojų padažas', 'Pantry', 'Oils & condiments'),
  ('Tamari', 'Pantry', 'Oils & condiments'),
  ('Coconut aminos', 'Pantry', 'Oils & condiments'),
  ('Actas', 'Pantry', 'Oils & condiments'),
  ('Balzaminis actas', 'Pantry', 'Oils & condiments'),
  ('Ryžių actas', 'Pantry', 'Oils & condiments'),
  ('Obuolių actas', 'Pantry', 'Oils & condiments'),
  ('Gochujang', 'Pantry', 'Oils & condiments'),
  ('Miso pasta', 'Pantry', 'Oils & condiments'),
  ('Tahini', 'Pantry', 'Oils & condiments'),
  ('Pomidorų pasta', 'Pantry', 'Oils & condiments'),
  ('Konservuoti pomidorai', 'Pantry', 'Oils & condiments'),
  ('Kokosų pienas', 'Pantry', 'Oils & condiments'),
  ('Kokosų kremas', 'Pantry', 'Oils & condiments'),
  ('Garstyčios', 'Pantry', 'Oils & condiments'),
  ('Veganiškas majonezas', 'Pantry', 'Oils & condiments'),
  ('Kečupas', 'Pantry', 'Oils & condiments'),
  ('Daržovių sultinys', 'Pantry', 'Oils & condiments'),
  ('Mielių dribsniai', 'Pantry', 'Oils & condiments'),
  ('Kario pasta', 'Pantry', 'Oils & condiments'),
  ('Curry roux', 'Pantry', 'Oils & condiments'),
  ('Alyvuogės', 'Pantry', 'Oils & condiments'),
  ('Kaparėliai', 'Pantry', 'Oils & condiments'),
  ('Marinuoti agurkai', 'Pantry', 'Oils & condiments'),
  ('Sriracha', 'Pantry', 'Oils & condiments'),
  ('Datulės', 'Pantry', 'Fruit'),
  ('Razinos', 'Pantry', 'Fruit'),
  ('Džiovintos slyvos', 'Pantry', 'Fruit'),
  ('Džiovinti abrikosai', 'Pantry', 'Fruit'),
  ('Cukrus', 'Pantry', 'Sweeteners'),
  ('Rudasis cukrus', 'Pantry', 'Sweeteners'),
  ('Medus', 'Pantry', 'Sweeteners'),
  ('Klevų sirupas', 'Pantry', 'Sweeteners'),
  ('Agavų sirupas', 'Pantry', 'Sweeteners'),
  ('Druska', 'Spices', 'Herbs & spices'),
  ('Juodieji pipirai', 'Spices', 'Herbs & spices'),
  ('Kuminas', 'Spices', 'Herbs & spices'),
  ('Rūkyta paprika', 'Spices', 'Herbs & spices'),
  ('Saldžioji paprika', 'Spices', 'Herbs & spices'),
  ('Ciberžolė', 'Spices', 'Herbs & spices'),
  ('Malta kalendra', 'Spices', 'Herbs & spices'),
  ('Čili milteliai', 'Spices', 'Herbs & spices'),
  ('Čili dribsniai', 'Spices', 'Herbs & spices'),
  ('Cinamonas', 'Spices', 'Herbs & spices'),
  ('Muskatas', 'Spices', 'Herbs & spices'),
  ('Lauro lapai', 'Spices', 'Herbs & spices'),
  ('Raudonėlis', 'Spices', 'Herbs & spices'),
  ('Džiovinti čiobreliai', 'Spices', 'Herbs & spices'),
  ('Imbiero milteliai', 'Spices', 'Herbs & spices'),
  ('Česnako milteliai', 'Spices', 'Herbs & spices'),
  ('Svogūnų milteliai', 'Spices', 'Herbs & spices'),
  ('Garam masala', 'Spices', 'Herbs & spices'),
  ('Kepimo milteliai', 'Spices', 'Herbs & spices'),
  ('Soda', 'Spices', 'Herbs & spices'),
  ('Tofu', 'Dairy & alternatives', 'Legumes'),
  ('Rūkytas tofu', 'Dairy & alternatives', 'Legumes'),
  ('Tempė', 'Dairy & alternatives', 'Legumes'),
  ('Seitanas', 'Dairy & alternatives', 'Legumes'),
  ('Augalinis sūris', 'Dairy & alternatives', 'Dairy alternatives'),
  ('Augalinė grietinėlė', 'Dairy & alternatives', 'Dairy alternatives'),
  ('Augalinis pienas', 'Dairy & alternatives', 'Dairy alternatives'),
  ('Avižinis pienas', 'Dairy & alternatives', 'Dairy alternatives'),
  ('Sojos pienas', 'Dairy & alternatives', 'Dairy alternatives'),
  ('Migdolų pienas', 'Dairy & alternatives', 'Dairy alternatives'),
  ('Augalinis jogurtas', 'Dairy & alternatives', 'Dairy alternatives'),
  ('Augalinis sviestas', 'Dairy & alternatives', 'Dairy alternatives'),
  ('Sūris', 'Dairy & alternatives', 'Other'),
  ('Fetos sūris', 'Dairy & alternatives', 'Other'),
  ('Mocarela', 'Dairy & alternatives', 'Other'),
  ('Parmezanas', 'Dairy & alternatives', 'Other'),
  ('Grietinėlė', 'Dairy & alternatives', 'Other'),
  ('Pienas', 'Dairy & alternatives', 'Other'),
  ('Jogurtas', 'Dairy & alternatives', 'Other'),
  ('Grietinė', 'Dairy & alternatives', 'Other'),
  ('Sviestas', 'Dairy & alternatives', 'Other'),
  ('Varškė', 'Dairy & alternatives', 'Other'),
  ('Kiaušiniai', 'Dairy & alternatives', 'Other'),
  ('Halloumi', 'Dairy & alternatives', 'Other'),
  ('Duona', 'Bakery', 'Grains'),
  ('Ruginė duona', 'Bakery', 'Grains'),
  ('Batonas', 'Bakery', 'Grains'),
  ('Tortilijos', 'Bakery', 'Grains'),
  ('Kukurūzų tortilijos', 'Bakery', 'Grains'),
  ('Pita duona', 'Bakery', 'Grains'),
  ('Naan duona', 'Bakery', 'Grains'),
  ('Bandelės', 'Bakery', 'Grains'),
  ('Šaldyti žirneliai', 'Frozen', 'Vegetables'),
  ('Šaldytos daržovės', 'Frozen', 'Vegetables'),
  ('Šaldyti špinatai', 'Frozen', 'Vegetables'),
  ('Šaldyti kukurūzai', 'Frozen', 'Vegetables'),
  ('Šaldytos bulvytės', 'Frozen', 'Vegetables'),
  ('Šaldytos uogos', 'Frozen', 'Fruit')
) as v(name, section, food_type)
on conflict do nothing;
