-- Expand the reviewed ingredient-to-category aliases without touching
-- a category selected by a household member.
--
-- Names are compared in the same accent-insensitive form used by the app's
-- mapper. The foreign key to barbora_categories rejects stale or invented
-- paths, and the distinct check keeps repeat runs quiet.

update public.ingredients ing set
  barbora_category_path = mapping.path,
  barbora_mapping_reason = 'alias',
  barbora_mapping_source = 'automatic',
  barbora_mapping_updated_at = now()
from (values
  ('kukuruzu tortilijos', '/duonos-gaminiai-ir-konditerija/duona/tortilijos-ir-picu-paplociai'),
  ('lavasas', '/duonos-gaminiai-ir-konditerija/duona/tortilijos-ir-picu-paplociai'),
  ('pita duona', '/duonos-gaminiai-ir-konditerija/duona/tortilijos-ir-picu-paplociai'),
  ('rugine duona', '/duonos-gaminiai-ir-konditerija/duona/tamsi-duona'),
  ('augaline grietinele', '/pieno-gaminiai-kiausiniai-ir-majonezas/augaliniai-produktai/augaliniai-gerimai-ir-grietinele'),
  ('augalinis jogurtas', '/pieno-gaminiai-kiausiniai-ir-majonezas/augaliniai-produktai/augaliniai-jogurto-ir-desertu-pakaitalai'),
  ('augalinis sviestas', '/pieno-gaminiai-kiausiniai-ir-majonezas/sviestas-margarinas-ir-riebalai/margarinas-ir-tepieji-riebalu-misiniai'),
  ('avizinis pienas', '/pieno-gaminiai-kiausiniai-ir-majonezas/augaliniai-produktai/augaliniai-gerimai-ir-grietinele'),
  ('migdolu pienas', '/pieno-gaminiai-kiausiniai-ir-majonezas/augaliniai-produktai/augaliniai-gerimai-ir-grietinele'),
  ('sojos pienas', '/pieno-gaminiai-kiausiniai-ir-majonezas/augaliniai-produktai/augaliniai-gerimai-ir-grietinele'),
  ('fetos suris', '/pieno-gaminiai-kiausiniai-ir-majonezas/suris/fetos-brinzos-ir-halumi-suriai'),
  ('grietinele', '/pieno-gaminiai-kiausiniai-ir-majonezas/grietine-ir-grietinele/grietinele'),
  ('jogurtas', '/pieno-gaminiai-kiausiniai-ir-majonezas/jogurtai-ir-desertai'),
  ('mocarela', '/pieno-gaminiai-kiausiniai-ir-majonezas/suris/mocarelos-ir-buratos-suriai'),
  ('parmezanas', '/pieno-gaminiai-kiausiniai-ir-majonezas/suris/kietieji-suriai'),
  ('varske', '/pieno-gaminiai-kiausiniai-ir-majonezas/varskes-produktai/varske'),
  ('seitanas', '/mesa-zuvis-ir-kulinarija/sviezia-mesa-ir-paukstiena/augaliniai-mesos-pakaitalai'),
  ('tempe', '/mesa-zuvis-ir-kulinarija/sviezia-mesa-ir-paukstiena/augaliniai-mesos-pakaitalai'),
  ('edamame', '/saldytas-maistas/saldytos-darzoves-vaisiai-ir-uogos/saldytos-darzoves-grybai-ir-ju-misiniai'),
  ('saldyti kukuruzai', '/saldytas-maistas/saldytos-darzoves-vaisiai-ir-uogos/saldytos-darzoves-grybai-ir-ju-misiniai'),
  ('saldyti spinatai', '/saldytas-maistas/saldytos-darzoves-vaisiai-ir-uogos/saldytos-darzoves-grybai-ir-ju-misiniai'),
  ('saldyti zirneliai', '/saldytas-maistas/saldytos-darzoves-vaisiai-ir-uogos/saldytos-darzoves-grybai-ir-ju-misiniai'),
  ('agavu sirupas', '/bakaleja/cukrus-druska-ir-kepimo-priedai/sirupai-ir-desertiniai-padazai'),
  ('klevu sirupas', '/bakaleja/cukrus-druska-ir-kepimo-priedai/sirupai-ir-desertiniai-padazai'),
  ('anakardziai', '/bakaleja/riesutai-seklos-dziovinti-vaisiai-ir-uogos/riesutai'),
  ('graikiniai riesutai', '/bakaleja/riesutai-seklos-dziovinti-vaisiai-ir-uogos/riesutai'),
  ('lazdyno riesutai', '/bakaleja/riesutai-seklos-dziovinti-vaisiai-ir-uogos/riesutai'),
  ('migdolai', '/bakaleja/riesutai-seklos-dziovinti-vaisiai-ir-uogos/riesutai'),
  ('pistacijos', '/bakaleja/riesutai-seklos-dziovinti-vaisiai-ir-uogos/riesutai'),
  ('zemes riesutai', '/bakaleja/riesutai-seklos-dziovinti-vaisiai-ir-uogos/riesutai'),
  ('aviziniai dribsniai', '/bakaleja/kruopos/avizines-kruopos-ir-dribsniai'),
  ('bulguras', '/bakaleja/kruopos/bulguro-ir-kuskuso-kruopos'),
  ('kuskusas', '/bakaleja/kruopos/bulguro-ir-kuskuso-kruopos'),
  ('kvinoja', '/bakaleja/kruopos/bolivine-balanda-soru-ir-kukuruzu-kruopos'),
  ('jazminu ryziai', '/bakaleja/kruopos/ilgagrudziai-ryziai'),
  ('rudieji ryziai', '/bakaleja/kruopos/rudieji-apvalieji-ir-kiti-ryziai'),
  ('susio ryziai', '/bakaleja/kruopos/plikyti-susiu-ir-rizoto-ryziai'),
  ('ryziai', '/bakaleja/kruopos'),
  ('raudonieji lesiai', '/bakaleja/kruopos/lesiai-avinzirniai-zirniai-ir-pupeles'),
  ('zali lesiai', '/bakaleja/kruopos/lesiai-avinzirniai-zirniai-ir-pupeles'),
  ('chia seklos', '/bakaleja/riesutai-seklos-dziovinti-vaisiai-ir-uogos/seklos-ir-ju-misiniai'),
  ('sezamai', '/bakaleja/riesutai-seklos-dziovinti-vaisiai-ir-uogos/seklos-ir-ju-misiniai'),
  ('saulegrazu seklos', '/bakaleja/riesutai-seklos-dziovinti-vaisiai-ir-uogos/seklos-ir-ju-misiniai'),
  ('linu semenys', '/bakaleja/riesutai-seklos-dziovinti-vaisiai-ir-uogos/selenos-ir-semenys'),
  ('datules', '/bakaleja/riesutai-seklos-dziovinti-vaisiai-ir-uogos/dziovinti-vaisiai'),
  ('dziovinti abrikosai', '/bakaleja/riesutai-seklos-dziovinti-vaisiai-ir-uogos/dziovinti-vaisiai'),
  ('dziovintos slyvos', '/bakaleja/riesutai-seklos-dziovinti-vaisiai-ir-uogos/dziovinti-vaisiai'),
  ('razinos', '/bakaleja/riesutai-seklos-dziovinti-vaisiai-ir-uogos/dziovinti-vaisiai'),
  ('darzoviu sultinys', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/sultiniai-ir-sultiniu-kubeliai'),
  ('grybu sultinys', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/sultiniai-ir-sultiniu-kubeliai'),
  ('kecupas', '/bakaleja/padazai-ir-konservuotos-uztepeles/kecupai'),
  ('pesto', '/bakaleja/padazai-ir-konservuotos-uztepeles/pesto-padazai'),
  ('pomidoru padazas', '/bakaleja/padazai-ir-konservuotos-uztepeles/pomidoru-padazai-ir-pasta'),
  ('pomidoru pasta', '/bakaleja/padazai-ir-konservuotos-uztepeles/pomidoru-padazai-ir-pasta'),
  ('tahini', '/bakaleja/padazai-ir-konservuotos-uztepeles'),
  ('veganiskas majonezas', '/pieno-gaminiai-kiausiniai-ir-majonezas/majonezas/majonezas'),
  ('kokosu aliejus', '/bakaleja/aliejus-ir-actas/kokosu-ir-kitu-riesutu-aliejus'),
  ('augalinis aliejus', '/bakaleja/aliejus-ir-actas'),
  ('sezamu aliejus', '/bakaleja/aliejus-ir-actas'),
  ('obuoliu actas', '/bakaleja/aliejus-ir-actas/actas-ir-citrinu-sultys'),
  ('ryziu actas', '/bakaleja/aliejus-ir-actas/actas-ir-citrinu-sultys'),
  ('lazanijos lakstai', '/bakaleja/makaronai/ilgieji-plokstieji-ir-lazanijos-makaronai'),
  ('spageciai', '/bakaleja/makaronai/ilgieji-plokstieji-ir-lazanijos-makaronai'),
  ('orzo', '/bakaleja/makaronai/trumpieji-ir-smulkieji-makaronai'),
  ('pilno grudo miltai', '/bakaleja/miltai-ir-ju-misiniai/kvietiniai-ir-ruginiai-miltai'),
  ('marinuoti agurkai', '/bakaleja/konservuotas-maistas/konservuoti-agurkai'),
  ('raudonosios pupeles', '/bakaleja/konservuotas-maistas/konservuotos-pupeles'),
  ('uogiene', '/bakaleja/konservuotas-maistas/uogienes-ir-dzemai'),
  ('brukniu uogiene', '/bakaleja/konservuotas-maistas/uogienes-ir-dzemai'),
  ('alyvuoges', '/bakaleja/konservuotas-maistas/konservuotos-alyvuoges-kapareliai-ir-svogunai'),
  ('riesutu sviestas', '/bakaleja/saldumynai/sokolado-ir-riesutu-kremai'),
  ('sojos kubeliai', '/mesa-zuvis-ir-kulinarija/sviezia-mesa-ir-paukstiena/augaliniai-mesos-pakaitalai'),
  ('soju farsas', '/mesa-zuvis-ir-kulinarija/sviezia-mesa-ir-paukstiena/augaliniai-mesos-pakaitalai'),
  ('soju kotletu misinys', '/mesa-zuvis-ir-kulinarija/sviezia-mesa-ir-paukstiena/augaliniai-mesos-pakaitalai'),
  ('nori lapai', '/mesa-zuvis-ir-kulinarija/kulinarija/susiai-ir-juros-kopustai'),
  ('baltas vynas', '/gerimai/vynas/baltasis-vynas'),
  ('raudonas vynas', '/gerimai/vynas/raudonasis-vynas'),
  ('tamsus alus', '/gerimai/alus/tamsusis-alus'),
  ('apelsinai', '/darzoves-ir-vaisiai/vaisiai-ir-uogos/citrusiniai-vaisiai'),
  ('citrinos', '/darzoves-ir-vaisiai/vaisiai-ir-uogos/citrusiniai-vaisiai'),
  ('laimai', '/darzoves-ir-vaisiai/vaisiai-ir-uogos/citrusiniai-vaisiai'),
  ('avietes', '/darzoves-ir-vaisiai/vaisiai-ir-uogos/vynuoges-ir-uogos'),
  ('braskes', '/darzoves-ir-vaisiai/vaisiai-ir-uogos/vynuoges-ir-uogos'),
  ('melynes', '/darzoves-ir-vaisiai/vaisiai-ir-uogos/vynuoges-ir-uogos'),
  ('granatai', '/darzoves-ir-vaisiai/vaisiai-ir-uogos/egzotiniai-vaisiai'),
  ('mangai', '/darzoves-ir-vaisiai/vaisiai-ir-uogos/egzotiniai-vaisiai'),
  ('bazilikas', '/darzoves-ir-vaisiai/darzoves-ir-grybai/prieskonines-darzoves-ir-zoleles'),
  ('ciobreliai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/prieskonines-darzoves-ir-zoleles'),
  ('kalendros lapai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/prieskonines-darzoves-ir-zoleles'),
  ('krapai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/prieskonines-darzoves-ir-zoleles'),
  ('metos', '/darzoves-ir-vaisiai/darzoves-ir-grybai/prieskonines-darzoves-ir-zoleles'),
  ('petrazoles', '/darzoves-ir-vaisiai/darzoves-ir-grybai/prieskonines-darzoves-ir-zoleles'),
  ('rozmarinas', '/darzoves-ir-vaisiai/darzoves-ir-grybai/prieskonines-darzoves-ir-zoleles'),
  ('salavijas', '/darzoves-ir-vaisiai/darzoves-ir-grybai/prieskonines-darzoves-ir-zoleles'),
  ('cili pipirai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/paprikos'),
  ('vysniniai pomidorai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/pomidorai-ir-agurkai'),
  ('kiniski kopustai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/bulves-morkos-ir-kopustai'),
  ('raudonieji kopustai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/bulves-morkos-ir-kopustai'),
  ('ziediniai kopustai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/bulves-morkos-ir-kopustai'),
  ('raudonieji svogunai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/svogunai-porai-ir-cesnakai'),
  ('zali svogunai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/svogunai-porai-ir-cesnakai'),
  ('ridikeliai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/burokeliai-ridikai-ir-imbieras'),
  ('pievagrybiai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/grybai'),
  ('sitake grybai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/grybai'),
  ('rukola', '/darzoves-ir-vaisiai/darzoves-ir-grybai/salotos-ir-ju-misiniai'),
  ('spinatai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/salotos-ir-ju-misiniai'),
  ('sparagines pupeles', '/darzoves-ir-vaisiai/darzoves-ir-grybai/kukuruzai-zirniai-pupeles-ir-smidrai'),
  ('brokoliai', '/darzoves-ir-vaisiai/darzoves-ir-grybai'),
  ('pastarnokai', '/darzoves-ir-vaisiai/darzoves-ir-grybai'),
  ('ropes', '/darzoves-ir-vaisiai/darzoves-ir-grybai'),
  ('saldziosios bulves', '/darzoves-ir-vaisiai/darzoves-ir-grybai'),
  ('salierai', '/darzoves-ir-vaisiai/darzoves-ir-grybai'),
  ('cukiniju ziedai', '/darzoves-ir-vaisiai/darzoves-ir-grybai'),
  ('juodieji pipirai', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/pipirai'),
  ('kajeno pipirai', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/pipirai'),
  ('cili dribsniai', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/pipirai'),
  ('cili milteliai', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/pipirai'),
  ('kario prieskoniai', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/prieskoniu-ir-zoleliu-misiniai'),
  ('tikka masala prieskoniai', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/prieskoniu-ir-zoleliu-misiniai'),
  ('cesnako milteliai', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/grynieji-prieskoniai-ir-zoleles'),
  ('ciberzole', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/grynieji-prieskoniai-ir-zoleles'),
  ('cinamonas', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/grynieji-prieskoniai-ir-zoleles'),
  ('dziovinti ciobreliai', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/grynieji-prieskoniai-ir-zoleles'),
  ('garstyciu seklos', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/grynieji-prieskoniai-ir-zoleles'),
  ('imbiero milteliai', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/grynieji-prieskoniai-ir-zoleles'),
  ('kuminas', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/grynieji-prieskoniai-ir-zoleles'),
  ('lauro lapai', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/grynieji-prieskoniai-ir-zoleles'),
  ('malta kalendra', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/grynieji-prieskoniai-ir-zoleles'),
  ('muskatas', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/grynieji-prieskoniai-ir-zoleles'),
  ('raudonelis', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/grynieji-prieskoniai-ir-zoleles'),
  ('rukyta paprika', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/grynieji-prieskoniai-ir-zoleles'),
  ('saldzioji paprika', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/grynieji-prieskoniai-ir-zoleles'),
  ('svogunu milteliai', '/bakaleja/prieskoniai-marinatai-ir-sultiniai/grynieji-prieskoniai-ir-zoleles'),
  ('druska', '/bakaleja/cukrus-druska-ir-kepimo-priedai/druska'),
  ('cukrus', '/bakaleja/cukrus-druska-ir-kepimo-priedai/baltasis-cukrus'),
  ('rudasis cukrus', '/bakaleja/cukrus-druska-ir-kepimo-priedai/rudasis-cukrus'),
  ('soda', '/bakaleja/cukrus-druska-ir-kepimo-priedai/soda-ir-krakmolas'),
  ('kukuruzu krakmolas', '/bakaleja/cukrus-druska-ir-kepimo-priedai/soda-ir-krakmolas'),
  ('kepimo milteliai', '/bakaleja/cukrus-druska-ir-kepimo-priedai/kepimo-milteliai-ir-vanilinis-cukrus'),
  ('soju padazas', '/bakaleja/padazai-ir-konservuotos-uztepeles/soju-terijakio-ir-vorcesterio-padazai'),
  ('tofu', '/pieno-gaminiai-kiausiniai-ir-majonezas/augaliniai-produktai/augalinis-suris-uztepai-ir-tofu'),
  ('rukytas tofu', '/pieno-gaminiai-kiausiniai-ir-majonezas/augaliniai-produktai/augalinis-suris-uztepai-ir-tofu'),
  ('augalinis pienas', '/pieno-gaminiai-kiausiniai-ir-majonezas/augaliniai-produktai/augaliniai-gerimai-ir-grietinele'),
  ('miltai', '/bakaleja/miltai-ir-ju-misiniai/kvietiniai-ir-ruginiai-miltai')
) as mapping(normalized_name, path)
where translate(lower(trim(ing.name)), 'ąčęėįšųūž', 'aceeisuuz') = mapping.normalized_name
  and ing.barbora_mapping_source is distinct from 'manual'
  and ing.barbora_category_path is distinct from mapping.path;
