-- Give the existing vocabulary the categories the mapper proposes for it.
--
-- Generated by running src/lib/barboraMapping.js over the household's 217
-- ingredients against the published catalogue, and reviewed one by one. Every
-- row here is an `exact` term match on Barbora's own category name, a reviewed
-- alias, or a retreat to a parent where the shop sells the thing in two
-- places. The remaining 151 ingredients keep their section's aisle link.
--
-- Idempotent, and it never touches a category a person chose by hand.

update public.ingredients ing set
  barbora_category_path = m.path,
  barbora_mapping_reason = m.reason,
  barbora_mapping_source = 'automatic',
  barbora_mapping_updated_at = now()
from (values
  ('Bandelės', '/duonos-gaminiai-ir-konditerija/bandeles-uzkandziai-ir-kibinai', 'exact'),
  ('Batonas', '/duonos-gaminiai-ir-konditerija/duona', 'parent_fallback'),
  ('Duona', '/duonos-gaminiai-ir-konditerija/duona', 'exact'),
  ('Tortilijos', '/duonos-gaminiai-ir-konditerija/duona/tortilijos-ir-picu-paplociai', 'exact'),
  ('Augalinis pienas', '/pieno-gaminiai-kiausiniai-ir-majonezas/augaliniai-produktai/augaliniai-gerimai-ir-grietinele', 'alias'),
  ('Augalinis sūris', '/pieno-gaminiai-kiausiniai-ir-majonezas/augaliniai-produktai/augalinis-suris-uztepai-ir-tofu', 'exact'),
  ('Grietinė', '/pieno-gaminiai-kiausiniai-ir-majonezas/grietine-ir-grietinele/grietine-ir-kastinys', 'exact'),
  ('Kiaušiniai', '/pieno-gaminiai-kiausiniai-ir-majonezas/kiausiniai', 'exact'),
  ('Pienas', '/pieno-gaminiai-kiausiniai-ir-majonezas/pienas', 'exact'),
  ('Rūkytas tofu', '/pieno-gaminiai-kiausiniai-ir-majonezas/augaliniai-produktai/augalinis-suris-uztepai-ir-tofu', 'alias'),
  ('Sūris', '/pieno-gaminiai-kiausiniai-ir-majonezas/suris', 'exact'),
  ('Sviestas', '/pieno-gaminiai-kiausiniai-ir-majonezas/sviestas-margarinas-ir-riebalai/sviestas', 'exact'),
  ('Tofu', '/pieno-gaminiai-kiausiniai-ir-majonezas/augaliniai-produktai/augalinis-suris-uztepai-ir-tofu', 'alias'),
  ('Šaldytos bulvytės', '/saldytas-maistas/saldytos-darzoves-vaisiai-ir-uogos/saldytos-bulvytes', 'exact'),
  ('Šaldytos daržovės', '/saldytas-maistas/saldytos-darzoves-vaisiai-ir-uogos/saldytos-darzoves-grybai-ir-ju-misiniai', 'exact'),
  ('Šaldytos uogos', '/saldytas-maistas/saldytos-darzoves-vaisiai-ir-uogos/saldytos-uogos-ir-vaisiai', 'exact'),
  ('Actas', '/bakaleja/aliejus-ir-actas/actas-ir-citrinu-sultys', 'exact'),
  ('Alyvuogių aliejus', '/bakaleja/aliejus-ir-actas/alyvuogiu-aliejus', 'exact'),
  ('Balzaminis actas', '/bakaleja/aliejus-ir-actas/balzaminis-actas', 'exact'),
  ('Basmati ryžiai', '/bakaleja/kruopos/basmati-ryziai', 'exact'),
  ('Cukrus', '/bakaleja/cukrus-druska-ir-kepimo-priedai/baltasis-cukrus', 'alias'),
  ('Garstyčios', '/bakaleja/padazai-ir-konservuotos-uztepeles/garstycios-ir-krienai', 'exact'),
  ('Grikiai', '/bakaleja/kruopos/grikiai', 'exact'),
  ('Kaparėliai', '/bakaleja/konservuotas-maistas/konservuotos-alyvuoges-kapareliai-ir-svogunai', 'exact'),
  ('Konservuoti pomidorai', '/bakaleja/konservuotas-maistas/konservuoti-pomidorai', 'exact'),
  ('Kukurūzų krakmolas', '/bakaleja/cukrus-druska-ir-kepimo-priedai/soda-ir-krakmolas', 'alias'),
  ('Kukurūzų kruopos', '/bakaleja/kruopos/bolivine-balanda-soru-ir-kukuruzu-kruopos', 'exact'),
  ('Lęšiai', '/bakaleja/kruopos/lesiai-avinzirniai-zirniai-ir-pupeles', 'exact'),
  ('Makaronai', '/bakaleja/makaronai', 'exact'),
  ('Medus', '/bakaleja/konservuotas-maistas/medus', 'exact'),
  ('Miltai', '/bakaleja/miltai-ir-ju-misiniai/kvietiniai-ir-ruginiai-miltai', 'alias'),
  ('Moliūgų sėklos', '/bakaleja/riesutai-seklos-dziovinti-vaisiai-ir-uogos/sudytos-kepintos-saulegrazu-ir-moliugu-seklos', 'exact'),
  ('Perlinės kruopos', '/bakaleja/kruopos/miezines-ir-perlines-kruopos', 'exact'),
  ('Pupelės', '/bakaleja/kruopos/lesiai-avinzirniai-zirniai-ir-pupeles', 'exact'),
  ('Rapsų aliejus', '/bakaleja/aliejus-ir-actas/rapsu-aliejus', 'exact'),
  ('Riešutai', '/bakaleja/riesutai-seklos-dziovinti-vaisiai-ir-uogos/riesutai', 'exact'),
  ('Rudasis cukrus', '/bakaleja/cukrus-druska-ir-kepimo-priedai/rudasis-cukrus', 'alias'),
  ('Saulėgrąžų aliejus', '/bakaleja/aliejus-ir-actas/saulegrazu-aliejus', 'exact'),
  ('Sojų padažas', '/bakaleja/padazai-ir-konservuotos-uztepeles/soju-terijakio-ir-vorcesterio-padazai', 'alias'),
  ('Žirniai', '/bakaleja/kruopos/lesiai-avinzirniai-zirniai-ir-pupeles', 'exact'),
  ('Agurkai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/pomidorai-ir-agurkai', 'exact'),
  ('Avokadai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/avokadai', 'exact'),
  ('Baklažanai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/moliugai-cukinijos-ir-baklazanai', 'exact'),
  ('Bananai', '/darzoves-ir-vaisiai/vaisiai-ir-uogos/bananai-obuoliai-ir-kriauses', 'exact'),
  ('Bulvės', '/darzoves-ir-vaisiai/darzoves-ir-grybai/bulves-morkos-ir-kopustai', 'exact'),
  ('Burokėliai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/burokeliai-ridikai-ir-imbieras', 'exact'),
  ('Česnakai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/svogunai-porai-ir-cesnakai', 'exact'),
  ('Cukinijos', '/darzoves-ir-vaisiai/darzoves-ir-grybai/moliugai-cukinijos-ir-baklazanai', 'exact'),
  ('Daržovės', '/darzoves-ir-vaisiai/darzoves-ir-grybai', 'exact'),
  ('Grybai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/grybai', 'exact'),
  ('Imbieras', '/darzoves-ir-vaisiai/darzoves-ir-grybai/burokeliai-ridikai-ir-imbieras', 'exact'),
  ('Kopūstai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/bulves-morkos-ir-kopustai', 'exact'),
  ('Kriaušės', '/darzoves-ir-vaisiai/vaisiai-ir-uogos/bananai-obuoliai-ir-kriauses', 'exact'),
  ('Kukurūzai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/kukuruzai-zirniai-pupeles-ir-smidrai', 'exact'),
  ('Moliūgai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/moliugai-cukinijos-ir-baklazanai', 'exact'),
  ('Morkos', '/darzoves-ir-vaisiai/darzoves-ir-grybai/bulves-morkos-ir-kopustai', 'exact'),
  ('Obuoliai', '/darzoves-ir-vaisiai/vaisiai-ir-uogos/bananai-obuoliai-ir-kriauses', 'exact'),
  ('Paprikos', '/darzoves-ir-vaisiai/darzoves-ir-grybai/paprikos', 'exact'),
  ('Pomidorai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/pomidorai-ir-agurkai', 'exact'),
  ('Porai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/svogunai-porai-ir-cesnakai', 'exact'),
  ('Salotos', '/darzoves-ir-vaisiai/darzoves-ir-grybai/salotos-ir-ju-misiniai', 'exact'),
  ('Svogūnai', '/darzoves-ir-vaisiai/darzoves-ir-grybai/svogunai-porai-ir-cesnakai', 'exact'),
  ('Vynuogės', '/darzoves-ir-vaisiai/vaisiai-ir-uogos/vynuoges-ir-uogos', 'exact'),
  ('Druska', '/bakaleja/cukrus-druska-ir-kepimo-priedai/druska', 'alias'),
  ('Kepimo milteliai', '/bakaleja/cukrus-druska-ir-kepimo-priedai/kepimo-milteliai-ir-vanilinis-cukrus', 'alias'),
  ('Soda', '/bakaleja/cukrus-druska-ir-kepimo-priedai/soda-ir-krakmolas', 'alias')
) as m(name, path, reason)
where lower(trim(ing.name)) = lower(trim(m.name))
  -- A hand-picked category is never overwritten by a backfill.
  and ing.barbora_mapping_source is distinct from 'manual';
